# Generated by Django 6.1 on 2026-08-30 03:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='account',
            name='accounts_ac_user_id_6d63db_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='accounts_ac_status_07de41_idx',
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'status'], name='accounts_ac_user_id_7fbf1c_idx'),
        ),
    ]
